---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  annotations:
    description: Configuration Map for gateway
data:
  accept.license: {{ .Values.gateway.license.accept | quote}}
  extra-java-args.env: {{ include "gateway.java.args" .}}
  ssg-jvm-heap.env: {{ .Values.gateway.heapSize }}
  log-override-properties: |+
    handlers = com.l7tech.server.log.GatewayRootLoggingHandler, com.l7tech.server.log.ConsoleMessageSink$L7ConsoleHandler
    com.l7tech.server.log.GatewayRootLoggingHandler.formatter = com.l7tech.util.JsonLogFormatter
    java.util.logging.SimpleFormatter.format=
    com.l7tech.server.log.ConsoleMessageSink$L7ConsoleHandler.formatter = com.l7tech.util.JsonLogFormatter
    com.l7tech.server.log.ConsoleMessageSink$L7ConsoleHandler.level = CONFIG
  {{- if .Files.Get "files/hazelcast-xml.xml" }}
  hazelcast-xml: |+
  {{- tpl (.Files.Get "files/hazelcast-xml.xml") . | nindent 4}}
  {{- end }}
  {{- if .Files.Get "files/metrics-bundle.xml" }}
  metrics-bundle: |+
{{- tpl (.Files.Get "files/metrics-bundle.xml") . | nindent 4}}
  {{- end }}
