---
apiVersion: v1
kind: Service
metadata:
  name: gw-{{ .Release.Namespace }}
  labels:
    app: gw-{{ .Release.Namespace }}
spec:
  selector:
    app: gw-{{ .Release.Namespace }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.gateway.service.loadBalancerIP }}
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  ports:
    {{- range .Values.gateway.service.ports }}
    - protocol: TCP
      port: {{ .external }}
      targetPort: {{ .internal }}
      name: {{ .name | quote }}
    {{- end }}