---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gateway-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.gateway.container: semver:*
#    flux.weave.works/ignore: "true"
spec:
  releaseName: gateway-dev
  forceUpgrade: true
  chart:
    git: git@github.com:david-dc-chen/puma-gitops
    path: charts/gateway
    ref: master
  valuesFrom:
  - secretKeyRef:
      name: image-creds
      key: image-creds.yaml
  - secretKeyRef:
      name: gateway-license
      key: license.yaml
  - secretKeyRef:
      name: env
      key: env.yaml
  values:
   gateway:
    replicaCount: 1
    container:
      image: docker.dev1.apimgcp.com/repository/docker-hosted/gateway
      tag: 'v4'
    imageCredentials:
      name: "docker.dev1.apimgcp.com"
      registry: "docker.dev1.apimgcp.com"
      username: "admin"
    hazelcast:
      enabled: false
    service:
      ports:
      - name: http
        internal: 8080
        external: 80
      - name: https
        internal: 8443
        external: 443





