apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgAaQQLjewKa+iS0C47Cl/r6mVKQ2gJT19VWbcZya5AoOT8fkgPFDttAmXnWwovHFgU6VGm4j9LWD21DcfVOx0sNbf7eUuHWvar95GcMODPjd4RbjzIL6Q6tDxLdpo3m+BTVErMNHtw/dCgItYl3rJf8CysvhFkZCbxqcS3H9i4t+3xoYAvoclXWcZpLuYwJGOpPPDRCIPxNHn7GPMHL4xOnPZsVEmOMGNZICzxSmb7roYi3L5ZazJJ9+y5mF4IKwpm6XTJWs/xTkWwoxeeGvbUsSv28agXVLNlwm3TCkeXJAKn5fjIzhytyvVxIelKk36anJVdKp2wq3SU6gLklrJL4AkWA+64KVq/TgdnvgpbnLQzeXO/JD05ZbIF/nyb6MHB+Bh6Gj5mOc0SGMZdgCceTNao5LfUIe5lhbP6fW+VuGGsRAGkWi7etUMEY8wdi7WTg8p2zNbXgWnAwn1lLKyjaJYhQRLRfSUL5j9t/eJIamg8jYpJgdY5GMmb/LCmxB6jUdALK014M/5J3TfPyqWuvU+kacRuZD/abjmVyCFI5AnLZXL+olFDAMGliaNXMJntQXjNZ4/U4NMj8DvCJdMgiPFVf6epOLoMy+NkLrGDjWZuD9f1zv/QjjaOo6SmBw0mBFPGmuNHtw/xcyslW37E9Z3avvzNgt526gwpg17os5GYDXNRd1K0vzK2na93LcJtltyn35PW8Zlqw9ZjFlwf8nzI/z4XVuQSByqcMhZWbhIdXjaZ5YCerpw==

