apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-creds
  namespace: dev
spec:
  encryptedData:
    image-creds.yaml: AgBvVhyAW1mldEKqbM57nmsNz8OqbqVb4hOLVa5qc3V8ivEzMlWKt1ZIMmPz/1sDb7QbOeXev25z64OUd1d7vkh8ObKqIkkpRttF1ew5pLLX0ydsEK53Z4I9PGtxf60Wrn6fb0JsjqRt28JbNrrdl5D5Yv39WHzUHDMXAiUEJtx7JBsJKnltA9bxgqqf4ZKuV1vfBFCzIO1D92OJPK2zTA0kpI9EwwfiF/gMTsiBWMygwYb6N1s1bwXAidGtAK0pn8Ozfw6p2mqGN9tHPLtn4Rl7ADw5xkbldFwxhtdFODDhRzG7c6b238mWs1BqbDjZA4D38biUMUnhpXCyymARyeudjDZhDkV47TJcp0nj8/XOrPE6T3DRu8voxNx3GT909NvjSJFPJgAD17hJs4QzZOMn4s7p1E++tuQK4qz0pB7sPKZ9/B26QBjSJqPUs+fDTiTvUQ7IJGwS9Yz/3+deeZDvAyewZZQ0uVpv2MnsAWd68lWqXiLcKuNBCAhHREfoK430bLu/vZDfp0iSs38DiNjTDICb1dPKh6ZvtgBKizh9kShhMC6HqPYuP2xYeZOfb29feK7L+lHpjzMV2SgvksZLAcph2qxPewdB1ofXoEUSXIAypd0aSO0vat3NHvDR4OFQSNZaozDFGkWoNR99roF1usjlhy1NorrcvrNT7hqzM8p7Z7Bdcdg/mSuZ7HkQbN60Ot97Ai/QmaMQ3XM/xRT9ULxsj+tuRVI78RHxuFSneY6el4oTsGppzaIbz96bPg7ErnZkgTZIig==

